version: 2

python:
  install:
    - requirements: docs/requirements.txt  # Install dependencies from requirements.txt
  tools:
    sphinx: "4.0"  # Specify the version of Sphinx (optional)

build:
  os: ubuntu-20.04  # Use the OS value for building the docs
  commands:
    - pip install -r docs/requirements.txt  # Install dependencies from requirements.txt
    - sphinx-build -b html docs/source docs/build/html  # Build the HTML docs

