version: 2

python:
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-20.04  # Correct OS value
  commands:
    - pip install -r docs/requirements.txt  # Install dependencies
    - sphinx-build -b html docs/source docs/build/html  # Build the HTML documentation

