version: 2

python:
  version: 3.10  # or any other version you prefer
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-20.04  # Correct OS value
  tools:
    sphinx: # Define sphinx as a dictionary
