# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04
  image: latest
  tools:
    python: "3.8"
  
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt  # if you have additional dependencies

