version: 2

# The language setting determines the version of Python to use
python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt
  build:
    os: ubuntu-20.04
    tools:
      - sphinx

