version: 2

# Python version and installation of dependencies
python:
  version: 3.10  # Specify the Python version (you can change it if needed)
  install:
    - requirements: docs/requirements.txt  # Install dependencies from docs/requirements.txt

# Build settings
build:
  os: ubuntu-20.04  # Specify the OS for the build (you can adjust this if needed)
  tools:
    sphinx: "4.0"  # Optional: Specify the version of Sphinx you want to use
  commands:
    - pip install -r docs/requirements.txt  # Install dependencies listed in requirements.txt
    - sphinx-build -b html docs/source docs/build/html  # Build the HTML docs

