name: geom_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.3
  - gmsh=4.11.1
  - ase=3.22.1
  - pytest=8.3.4
  - rdkit=2025.03.6
  - pip
  - pip:
      - launchpadlib==2.1.0
      - openai==1.3.8
      - pyautogen==0.2.18
      - flaml[automl]==2.1.1
      - httpx==0.27.2 # Needed to eliminate proxis problem
